// Order Status Constants
export const ORDER_STATUSES = {
  RECEIVED: "RECEIVED",
  INVENTORY_CHECK: "INVENTORY_CHECK",
  AWAITING_MATERIAL: "AWAITING_MATERIAL",
  READY_FOR_PRODUCTION: "READY_FOR_PRODUCTION",
  IN_PRODUCTION: "IN_PRODUCTION",
  PRODUCTION_COMPLETED: "PRODUCTION_COMPLETED",
  AWAITING_CLIENT_APPROVAL: "AWAITING_CLIENT_APPROVAL",
  REWORK_REQUIRED: "REWORK_REQUIRED",
  CLIENT_APPROVED: "CLIENT_APPROVED",
  DISPATCHED: "DISPATCHED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
}

// Production Step Types
export const PRODUCTION_STEPS = {
  CUTTING_FABRIC: "CUTTING_FABRIC",
  BASE_STITCHING: "BASE_STITCHING",
  EMBROIDERY: "EMBROIDERY",
  COMPONENT_PREP: "COMPONENT_PREP",
  LACE_ATTACH: "LACE_ATTACH",
  FINAL_ASSEMBLY: "FINAL_ASSEMBLY",
  FINAL_QC: "FINAL_QC",
}

// Permission Codes (we'll expand these as we build)
export const PERMISSIONS = {
  ORDERS_VIEW: "ORDERS_VIEW",
  ORDERS_EDIT: "ORDERS_EDIT",
  ORDERS_CREATE: "ORDERS_CREATE",
  ORDERS_CHANGE_STATUS: "ORDERS_CHANGE_STATUS",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_UPDATE_STOCK: "INVENTORY_UPDATE_STOCK",
  TASKS_VIEW_ASSIGNED: "TASKS_VIEW_ASSIGNED",
  TASKS_VIEW_ALL: "TASKS_VIEW_ALL",
  TASKS_CREATE: "TASKS_CREATE",
  TASKS_UPDATE_STATUS: "TASKS_UPDATE_STATUS",
  QA_UPLOAD_VIDEO: "QA_UPLOAD_VIDEO",
  REPORTS_VIEW: "REPORTS_VIEW",
  ADMIN_USERS: "ADMIN_USERS",
  ADMIN_SETTINGS: "ADMIN_SETTINGS",
}